In [150]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pyplot
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [151]:
df=pd.read_csv("movies_metadata.csv")

In [152]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [153]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [154]:
df.shape

(45466, 24)

In [155]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [156]:
update_df=df[['title','overview','genres','tagline','production_companies','spoken_languages','vote_average','popularity']]

In [157]:
update_df.head()

,title,overview,genres,tagline,production_companies,spoken_languages,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_639_1': 'en', 'name': 'English'}]",7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_639_1': 'en', 'name': 'English'}]",6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,[{'name': 'Twentieth Century Fox Film Corporat...,"[{'iso_639_1': 'en', 'name': 'English'}]",6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,"[{'name': 'Sandollar Productions', 'id': 5842}...","[{'iso_639_1': 'en', 'name': 'English'}]",5.7,8.387519

In [158]:
update_df.isnull().sum()

title                       6
overview                  954
genres                      0
tagline                 25054
production_companies        3
spoken_languages            6
vote_average                6
popularity                  5
dtype: int64

In [159]:
update_df.duplicated().sum()

np.int64(13)

In [160]:
# delete duplicate rows
update_df.drop_duplicates(inplace=True)

In [161]:
update_df = update_df.dropna(subset=['title'])

In [162]:
update_df['overview']=update_df['overview'].fillna('')

In [163]:
update_df['tagline']=update_df['tagline'].fillna('')

In [164]:
import ast

In [165]:
update_df['genres'] = update_df['genres'].apply(
    lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]) if x != 'NaN' else ''
)

In [166]:
update_df['production_companies'] = update_df['production_companies'].apply(
    lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]) if x != 'NaN' else ''
)

In [167]:
update_df['spoken_languages'] = update_df['spoken_languages'].apply(
    lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]) if x != 'NaN' else ''
)

In [168]:
update_df['tags']=update_df['overview']+update_df['genres']+update_df['tagline']+update_df['production_companies']+update_df['spoken_languages']

In [169]:
update_df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.Adventure Fantasy FamilyRoll the dice and unleash the excitement!TriStar Pictures Teitler Film Interscope CommunicationsEnglish Français"

In [170]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [171]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [172]:
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [173]:
def preprocess_text(text):
  text=text.lower()
  text = re.sub(r'[^\w\s]', '', text)
  words=text.split()

  words=[word for word in words if word not in stop_words]
  words=[lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [174]:
update_df['tags']=update_df['tags'].apply(preprocess_text)

In [175]:
update_df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creaturesadventure fantasy familyroll dice unleash excitementtristar picture teitler film interscope communicationsenglish français'

In [176]:
update_df=update_df.reset_index(drop=True)

In [177]:
indices=pd.Series(update_df.index,update_df['title']).drop_duplicates()

In [178]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [179]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [184]:
tfidf=TfidfVectorizer(ngram_range=(1,2), max_features=80000,stop_words='english')

In [185]:
tfidf_matrix=tfidf.fit_transform(update_df['tags'])

In [186]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1643440 stored elements and shape (45447, 80000)>

In [187]:
from sklearn.metrics.pairwise import cosine_similarity

In [194]:
def recommend(title,n=10):
  if title not in indices:
    return "Movie not found"
  idx=indices[title]
  sim_scores=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  movie_indices=sim_scores.argsort()[::-1][1:n+1]
  return update_df['title'].iloc[movie_indices]

In [193]:
recommend('Avatar')

13562              Dragonball Evolution
11442                            Eragon
13125                         Australia
11918             Live Free or Die Hard
19175                         The Watch
26547                          Avatar 2
16343                Gulliver's Travels
17583    Rise of the Planet of the Apes
10970             X-Men: The Last Stand
15483                    Knight and Day
Name: title, dtype: object

In [195]:
import pickle

In [196]:
pickle.dump(tfidf,open('tfidf.pkl','wb'))

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

pickle.dump(update_df,open('update_df.pkl','wb'))